# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cb86787a3be4ea193c53bc46475bd0de4ebd602860782a82e4b39d35b323c3869e07d151f3d91b55b2e9d9c15bf87f1e92493accbb49612074206a93d83fed9

test:
  secret_key_base: 461284eec70e90b68e8c651a20b04809c374d2b48649bdfd58cfc913b9b69528b8ff50f59489484833af4c7549e23b869c9a3e36cc345a10e0343477d073f3f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
